<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPufc7wL\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPufc7wL/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPufc7wL.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPufc7wL\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPufc7wL\App_KernelProdContainer([
    'container.build_hash' => 'Pufc7wL',
    'container.build_id' => '214fb01c',
    'container.build_time' => 1744972543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPufc7wL');
