<?php

namespace ContainerPufc7wL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ApplicationsRepository' shared autowired service.
     *
     * @return \App\Repository\ApplicationsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ApplicationsRepository'] = new \App\Repository\ApplicationsRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
