<?php

namespace ContainerPufc7wL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\auth\AuthController' shared autowired service.
     *
     * @return \App\Controller\auth\AuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\auth\\AuthController'] = $instance = new \App\Controller\auth\AuthController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\auth\\AuthController', $container));

        return $instance;
    }
}
