<?php

namespace ContainerPufc7wL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizerControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\organizer\OrganizerController' shared autowired service.
     *
     * @return \App\Controller\organizer\OrganizerController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\organizer\\OrganizerController'] = $instance = new \App\Controller\organizer\OrganizerController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\organizer\\OrganizerController', $container));

        return $instance;
    }
}
