<?php

namespace ContainerPufc7wL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\profile\ProfileController' shared autowired service.
     *
     * @return \App\Controller\profile\ProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\profile\\ProfileController'] = $instance = new \App\Controller\profile\ProfileController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\profile\\ProfileController', $container));

        return $instance;
    }
}
