<?php

namespace ContainerPufc7wL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\social\SocialController' shared autowired service.
     *
     * @return \App\Controller\social\SocialController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\social\\SocialController'] = $instance = new \App\Controller\social\SocialController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\social\\SocialController', $container));

        return $instance;
    }
}
