<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxzrg4R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxzrg4R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKxzrg4R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKxzrg4R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKxzrg4R\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kxzrg4R',
    'container.build_id' => '962d4498',
    'container.build_time' => 1745872470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxzrg4R');
