<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app-root' => [[], ['_controller' => 'App\\Controller\\RootController::index'], [], [['text', '/']], [], [], []],
    'app_auth' => [[], ['_controller' => 'App\\Controller\\auth\\AuthController::index'], [], [['text', '/auth']], [], [], []],
    'app_chatbot' => [[], ['_controller' => 'App\\Controller\\chatbot\\ChatbotController::index'], [], [['text', '/chatbot']], [], [], []],
    'app_create_job' => [[], ['_controller' => 'App\\Controller\\create_job\\CreateJobController::index'], [], [['text', '/create/job']], [], [], []],
    'app_events' => [[], ['_controller' => 'App\\Controller\\events\\EventsController::index'], [], [['text', '/events']], [], [], []],
    'app_explore' => [[], ['_controller' => 'App\\Controller\\explore\\ExploreController::index'], [], [['text', '/explore']], [], [], []],
    'app_group' => [[], ['_controller' => 'App\\Controller\\group\\GroupController::index'], [], [['text', '/group']], [], [], []],
    'app_job_applications' => [[], ['_controller' => 'App\\Controller\\jobapplications\\JobApplicationsController::index'], [], [['text', '/job/applications']], [], [], []],
    'app_job_feed' => [[], ['_controller' => 'App\\Controller\\jobfeed\\JobFeedController::index'], [], [['text', '/job/feed']], [], [], []],
    'app_messagerie' => [[], ['_controller' => 'App\\Controller\\messagerie\\MessagerieController::index'], [], [['text', '/messagerie']], [], [], []],
    'app_organizer' => [[], ['_controller' => 'App\\Controller\\organizer\\OrganizerController::index'], [], [['text', '/organizer']], [], [], []],
    'app_profile' => [[], ['_controller' => 'App\\Controller\\profile\\ProfileController::index'], [], [['text', '/profile']], [], [], []],
    'app_social' => [[], ['_controller' => 'App\\Controller\\social\\SocialController::index'], [], [['text', '/social']], [], [], []],
];
